baseURL = "localhost:1313"
languageCode = "en-us"
title = "Systematik"
theme = "systematik"

[[menu.main]]
    name = "Home"
    title = "Home Section"
    weight = 1
    identifier = "home"
    url = "/"
    
[[menu.main]]
    name = "Om"
    title = "Om Section"
    weight = 2
    identifier = "Om"
    url = "/om/"
    
[[menu.main]]
    name = "Dokumentation"
    title = "dokumentation Section"
    weight = 3
    identifier = "dokumentation"
    url = "/docs/"